default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password: 123
  pool: 5


development:
  <<: *default
  database: mydiario_development

test:
  <<: *default
  database: mydiario_test

production:
  <<: *default
  database: mydiario_production
  username: mydiario
  password: <%= ENV['MYDIARIO_DATABASE_PASSWORD'] %>
